### ISSUE TITLE
Allow to filter out non protein coding variants in the transcripts plot

### ISSUE THREAD

**Issue by AMCalejandro** [RajLabMSSM/echoplot#2]
**Is your feature request related to a problem? Please describe.**

By exploring the filtering process in the txdb transcripts df derived from ensembldb, I thought of enhancement for this plot
I have noticed the transcripts plot gets overpopulated and tough to ready ( ie gene names overlapping)

**Describe alternatives you've considered**
Adding a flat to PLOT.locus( ..., prot_coding = T, ...), could allow the user to retrieve protein coding variants only.
The filtering could be performed while querying ensembldb object

**Comment by bschilder** [comment]
Now implemented in `echoplot` 0.99.5 via the new argument `plot_locus(tx_biotypes=<character vector>)`. 
You can see all the available transcript biotypes using the new function `get_tx_biotypes()`.

I'll modify `echolocatoR::finemap_loci` so that this argument can be passed up to that function as well.
